spring:
  application:
    name: payment-service-app
  server:
    port: 8080
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect